FROM python:3.11-slim

WORKDIR /mlflow

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir \
    mlflow>=2.11.0 \
    psycopg2-binary>=2.9.9 \
    "psycopg[binary]>=3.1.0" \
    boto3>=1.34.0

EXPOSE 5000
