apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-s3-sa
  namespace: leadsentry-serving
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/LeadSentryKServeS3ReadRole"
