apiVersion: v1
kind: Service
metadata:
  name: leadsentry-api-svc
  namespace: leadsentry-prod
  labels:
    app: leadsentry-api
spec:
  type: ClusterIP
  selector:
    app: leadsentry-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
