apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leadsentry-api-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/your-username/leadsentry.git"
    targetRevision: main
    path: k8s/serving
  destination:
    server: "https://kubernetes.default.svc"
    namespace: leadsentry-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
